Assignment-5 Search Functionality
roshantrivedi/REACT_18 pull request #5
Opened 2022-12-04 13:11 UTC by roshantrivedi

2022-12-04 16:32 UTC, ap221882 reviewed
Nicely written. Added some suggestions.

2022-12-04 16:32 UTC, ap221882 commented on React_Day5/avengers/src/App.css
> +h1{
Keep your html tag, *, body css selectors on top.

2022-12-04 16:32 UTC, ap221882 commented on React_Day5/avengers/src/Components/BodyComponent.js
> +import { useState } from "react";
Keep your global imports on the top.

2022-12-04 16:32 UTC, ap221882 commented on React_Day5/avengers/src/Components/BodyComponent.js
> +                ))}
Don't keep your index of map when iterating as a key to React element.

2022-12-04 16:32 UTC, ap221882 commented on React_Day5/avengers/src/Components/CardComponent.js
> +        <h5>{name}</h5>
Img is a self closing tag

2022-12-04 16:32 UTC, ap221882 commented on React_Day5/avengers/src/Components/HeadingComponent.js
> +      <h1>{title}</h1>
You can remove the React Fragment here

2022-12-04 16:32 UTC, ap221882 commented on React_Day5/avengers/public/index.html
> +      content="Web site created using create-react-app"
Change the description of your web app

2022-12-04 16:32 UTC, ap221882 commented on React_Day5/avengers/src/Components/SearchBarComponent.js
> +  return data.filter((team)=> team.name.toLowerCase().includes(searchText));
Make this an reusable/generic function. Keep this as separate utility function.

2022-12-04 18:50 UTC, nitishnivedan commented on React_Day5/avengers/src/Components/CardComponent.js
> +const CardComponent = ({avenger}) =>  {
can de structure further. e.g.
const cardComponent  = ({avengers:{img,name,company}}) => (
<div>

</div>
);

2022-12-04 18:56 UTC, nitishnivedan commented on React_Day5/avengers/src/Components/SearchBarComponent.js
> +        e.preventDefault();
can call a separate function for onSubmit event handler.

2022-12-04 18:57 UTC, nitishnivedan commented on React_Day5/avengers/src/index.js
> +import ReactDOM from 'react-dom/client';
can have an empty line between library imports and local file imports.

2022-12-05 13:55 UTC, laxmi20936 commented on React_Day5/avengers/src/Components/CardComponent.js
> +        <h5>{name}</h5>
Also give alt attribute to img tag

2022-12-06 05:41 UTC, Pujarini requested changes

2022-12-06 05:41 UTC, Pujarini commented on React_Day5/avengers/src/Components/BodyComponent.js
> +                {avengersData.map((i, index) => (
What if Avengers data is empty? The application will break then

2022-12-06 05:41 UTC, Pujarini commented on React_Day5/avengers/src/Components/SearchBarComponent.js
> +  return data.filter((team)=> team.name.toLowerCase().includes(searchText));
What  if team. name does not exist? It will break the application. Try using optional chaining.

2022-12-12 12:00 UTC, merged